name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU for cross-platform builds
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: __token__
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image (DE)
      uses: docker/build-push-action@v2
      with:
        context: languages/de/docker
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest-de
          ghcr.io/${{ github.repository }}:${{ github.sha }}-de
        platforms: linux/amd64,linux/arm64
        labels: |
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.created_at }}
    - name: Build and push Docker image (EN)
      uses: docker/build-push-action@v2
      with:
        context: docker
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest-en
          ghcr.io/${{ github.repository }}:${{ github.sha }}-en
        platforms: linux/amd64,linux/arm64
        labels: |
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.created_at }}
    - name: Build and push Docker image (DE-custom)
      uses: docker/build-push-action@v2
      with:
        context: languages/de-custom/docker
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest-de-custom
          ghcr.io/${{ github.repository }}:${{ github.sha }}-de-custom
        platforms: linux/amd64,linux/arm64
        labels: |
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ github.event.created_at }}
